const TEMPLATES = [
  {
    "category": "ENT",
    "title": "URTI / Viral Illness",
    "keywords": "urti viral cough sore throat fever flu covid influenza runny nose",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of throat pain, body pain, cough, runny nose and fever.\n\nContact with sick contacts / denied contact with sick contacts.\n\nRecent travel / no recent travel.\n\nDenied chest pain, SOB, vomiting, abdominal pain, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\n\nThroat: congested.\nCentral uvula.\n\nEars: intact TM.\nNo signs of mastoiditis.\n\nNo cervical lymphadenopathy.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\nPA: soft, lax, non-tender.",
    "mdm": "Presentation most consistent with upper respiratory tract infection / viral illness.\n\nDifferential diagnoses considered including viral URTI, influenza, COVID-19, streptococcal pharyngitis, tonsillitis, pneumonia and other respiratory tract infections as appropriate to presentation.\n\nInvestigations reviewed and explained if performed.\n\nNo evidence of severe infection, respiratory distress or other emergency condition requiring admission at present.",
    "discharge": "Feels better.\n\nSafety ER return instructions explained including shortness of breath, chest pain, persistent fever, difficulty swallowing, persistent vomiting, reduced oral intake or any other concerns.\n\nFollow up with ENT as needed."
  },
  {
    "category": "Trauma",
    "title": "Trauma Assessment (Primary + Secondary Survey)",
    "keywords": "trauma primary survey secondary survey head to toe xabcde",
    "history": "",
    "exam": "PRIMARY SURVEY (XABCDE)\n\nX - Exsanguinating Hemorrhage:\nNo massive external hemorrhage identified.\n\nA - Airway:\nPatent, speaking normally.\nNo stridor, no obstruction, no C-spine tenderness.\n\nB - Breathing:\nEqual air entry bilaterally.\nNo wheeze/crackles.\nNo tracheal deviation.\nNo chest wall deformity, no flail segment.\nO2 saturation reviewed.\n\nC - Circulation:\nHR and BP reviewed, hemodynamically stable.\nNo external hemorrhage.\nCapillary refill < 2 seconds.\nPeripheral pulses palpable.\n\nD - Disability:\nGCS 15/15 (E4 V5 M6).\nPERRLA.\nMoving all four limbs.\nBlood glucose reviewed.\n\nE - Exposure:\nFully exposed and log-rolled.\nNo obvious deformities, wounds, or bruising on exposure.\nTemperature reviewed, normothermic.\n\nSECONDARY SURVEY (Head to Toe)\n\nHead/Face:\nNo scalp lacerations, swelling, or step-offs.\nPupils equal and reactive.\nNo periorbital/raccoon eyes, no Battle's sign.\nNo nasal/septal deformity.\nNo midface instability.\nNo dental trauma.\n\nNeck:\nNo midline cervical tenderness.\nNo tracheal deviation.\nNo JVD.\nFull range of motion if cleared clinically.\n\nChest:\nNo chest wall tenderness, no crepitus, no flail segment.\nEqual air entry, no added sounds.\nHeart sounds normal, no muffled sounds.\n\nAbdomen:\nSoft, non-distended.\nNo tenderness, guarding, or rigidity.\nNo seatbelt sign or bruising.\nPelvis stable, non-tender to compression.\n\nBack/Spine:\nNo midline spinal tenderness or step-off on log roll.\nNo flank bruising.\n\nExtremities:\nNo deformity, swelling, or open wounds.\nFull range of motion in all limbs.\nNeurovascularly intact distally - pulses, sensation, motor function all preserved.\n\nNeurological:\nAlert and oriented x3.\nNo focal motor or sensory deficit.\nNormal speech.\nNo signs of head injury deterioration.\n\nPerineum/Rectal (if indicated):\nNo blood at urethral meatus.\nRectal exam deferred / performed - findings documented.",
    "mdm": "",
    "discharge": ""
  },
  {
    "category": "Cardio",
    "title": "Suspected DVT / Unilateral Leg Swelling",
    "keywords": "dvt deep vein thrombosis unilateral leg swelling swollen leg calf swelling calf pain tense calf doppler ultrasound venous thrombosis wells ocp",
    "history": "Patient is a ___-year-old male/female, known to have ______ / medically free. No known drug allergies / allergic to ______.\n\nPresented to the ED with right / left lower limb swelling, which started at approximately ______ while ______.\n\nAssociated with calf pain / tightness / heaviness / none as documented.\n\nNo history of trauma or fall.\nNo recent prolonged travel, surgery, fracture, or limb immobilization/cast.\nNo previous history of DVT/PE.\nCurrently on OCP / HRT / not on hormonal therapy.\n\nDenied fever, chest pain, shortness of breath, hemoptysis, syncope, or other associated symptoms.",
    "exam": "Conscious, alert and oriented x3, not in distress.\nGCS 15/15.\nHemodynamically stable.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\n\nRight / Left lower limb:\nVisibly swollen compared with the contralateral limb.\nCalf tense with tenderness / no tenderness.\nNo erythema or increased warmth.\nNo open wounds or obvious traumatic injury.\nPeripheral pulses palpable and intact bilaterally.\nDistal neurovascular examination intact.\n\nContralateral lower limb appears normal.",
    "mdm": "Acute unilateral lower limb swelling with clinical concern for deep vein thrombosis (DVT).\n\nRisk factors reviewed, including OCP/HRT use, recent surgery or immobilization, prolonged travel, previous DVT/PE, malignancy, pregnancy/postpartum state, and thrombophilia.\n\nDifferential diagnoses include DVT, superficial thrombophlebitis, cellulitis, ruptured Baker cyst, soft-tissue/muscular injury or hematoma, and venous insufficiency.\n\nD-dimer and/or venous Doppler ultrasound requested as clinically indicated based on pre-test probability.\n\nCurrently no reported symptoms suggestive of pulmonary embolism, including chest pain, shortness of breath, hemoptysis, or syncope.",
    "discharge": "Investigation results and clinical impression explained to the patient.\n\nIf DVT excluded and patient suitable for discharge, follow-up and further evaluation advised as clinically appropriate.\n\nSafety ER return instructions explained, including new or worsening chest pain, shortness of breath, hemoptysis, syncope, increasing leg swelling or pain, limb discoloration, numbness/weakness, fever, or any other concerns.\n\nIf DVT is confirmed or remains clinically suspected with pending/incomplete imaging, management and disposition to follow the appropriate anticoagulation, imaging, referral, and local protocol.",
    "insurance": "VENOUS DOPPLER ULTRASOUND — IMAGING / INSURANCE JUSTIFICATION\n\nPatient presents with acute unilateral lower limb swelling with objective asymmetry and a tense/swollen calf. In the presence of thromboembolic risk factors, including OCP use where applicable, DVT needs to be excluded.\n\nVenous Doppler ultrasound of the affected lower limb is clinically indicated to confirm or exclude deep venous thrombosis and guide further management."
  },
  {
    "category": "GI",
    "title": "Acute Gastroenteritis",
    "keywords": "gastroenteritis diarrhea vomiting dehydration age watery stools",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of vomiting and diarrhea.\n\nReports ___ episodes of watery, non-bloody diarrhea and ___ episodes of non-bilious, non-bloody vomiting.\n\nAssociated with generalized abdominal discomfort / cramping.\n\nContact with sick contacts / denied contact with sick contacts.\n\nRecent travel / no recent travel.\n\nRecent dietary indiscretion / no recent dietary change.\n\nDenied fever, blood in stool or vomit, urinary symptoms, chest pain, SOB, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\n\nHydration status: mucous membranes moist, no signs of dehydration / mild dehydration as documented.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\nPA: soft, lax, generalized mild tenderness / non-tender, no guarding, no rigidity, no rebound tenderness, bowel sounds present.",
    "mdm": "Presentation most consistent with acute gastroenteritis.\n\nDifferential diagnoses considered including appendicitis, bowel obstruction, pancreatitis, biliary pathology, colitis, food poisoning, dehydration and electrolyte disturbance as appropriate.\n\nInvestigations and treatment response reviewed if performed.\n\nNo evidence of acute surgical abdomen or severe dehydration requiring admission at present.",
    "discharge": "Feels better.\n\nOral hydration advised.\n\nSafety ER return instructions explained including worsening abdominal pain, persistent vomiting, inability to tolerate fluids, blood in stool or vomit, reduced urine output, fever, dizziness, or any other concerns.\n\nFollow up with primary care if symptoms persist."
  },
  {
    "category": "Cardio",
    "title": "Chest Pain",
    "keywords": "chest pain acs mi angina troponin ecg pe aortic pneumothorax",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ hours/days history of chest pain.\n\nPain described as ______, located ______, radiating to ______.\n\nAssociated with SOB / diaphoresis / nausea / vomiting / palpitations as documented.\n\nWorse with exertion / breathing / position / palpation / not related to exertion as documented.\n\nNo prior similar episodes / similar to prior episode in ______, worked up with ______.\n\nDenied syncope, hemoptysis, unilateral leg swelling, fever, recent immobilization, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\nHemodynamically stable, vital signs reviewed.\n\nCVS: S1 + S2, no murmur, regular rate and rhythm, no JVD, peripheral pulses palpable, no peripheral edema.\nChest: equal air entry bilaterally, no wheeze, no crackles, no added sounds, no chest wall tenderness reproducing pain.\nPA: soft, lax, non-tender.\nExtremities: no calf tenderness or swelling, no asymmetry.",
    "mdm": "Life-threatening causes considered including ACS, PE, aortic pathology, pneumothorax, pneumonia, pericarditis/myocarditis and other causes as appropriate.\n\nECG, troponin and relevant investigations reviewed and explained.\n\nRisk assessment documented as appropriate.\n\nNo current evidence of acute life-threatening cause requiring admission at present based on current assessment.",
    "discharge": "Feels better, no ongoing chest pain at time of discharge.\n\nSafety ER return instructions explained including recurrent/worsening chest pain, SOB, syncope, palpitations, diaphoresis, vomiting, or any other concerns.\n\nFollow up with primary care/cardiology as appropriate."
  },
  {
    "category": "MSK",
    "title": "Low Back Pain / Sciatica",
    "keywords": "back pain sciatica radiculopathy cauda equina red flags lumbar",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of lower back pain.\n\nPain radiates to right / left lower limb / no radiation as documented.\n\nAssociated with numbness / tingling / no numbness as documented.\n\nNo history of trauma / mechanism: ______.\n\nDenied fever, weight loss, IV drug use, steroid use, malignancy history, saddle anesthesia, urinary retention or incontinence, fecal incontinence, or progressive leg weakness.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\n\nBack: lumbar / paraspinal tenderness over ______, range of movement limited by pain, no deformity, no skin changes.\n\nLower limb neuro: power 5/5 bilaterally, sensation intact bilaterally, reflexes symmetrical, straight leg raise positive / negative as documented, gait assessed - normal.\n\nNo saddle anesthesia, no perianal sensory deficit, no urinary retention on bladder scan if performed.",
    "mdm": "Differential diagnoses considered including mechanical low back pain, sciatica/radiculopathy, renal colic, pyelonephritis, vertebral fracture, spinal infection, malignancy, and cauda equina syndrome.\n\nRed flags reviewed and absent unless otherwise documented.\n\nNo current evidence of cauda equina syndrome, spinal infection, fracture, or other emergency pathology requiring admission at present.\n\nPatient and family counselled regarding the following:\n\n1. Admission for analgesia and pain management: Should admission be required for pain control, it was explained that our facility does not have a dedicated spinal/orthopedic spine surgeon on a full-time basis. In such cases, orthopedic admission may not be feasible and transfer to an appropriate facility may be required. Patient verbalized understanding.\n\n2. Cauda equina syndrome / surgical emergency: In the event that MRI confirms cauda equina syndrome or other surgical spinal pathology requiring urgent neurosurgical or spinal surgical intervention, the patient will require transfer to SMC where the appropriate surgical services are available. Patient was informed of this possibility and agreed to proceed with imaging at this stage.",
    "discharge": "Feels better.\n\nAnalgesia, activity advice (early mobilization) and follow-up explained.\n\nSafety ER return instructions explained including new or worsening leg weakness, numbness, saddle anesthesia, urinary retention/incontinence, fecal incontinence, fever, worsening severe pain, inability to mobilize, or any other concerns.\n\nFollow up with primary care/physiotherapy as appropriate."
  },
  {
    "category": "Nephro",
    "title": "Renal Colic",
    "keywords": "renal colic ureteric stone flank loin hematuria kidney stone nephrolithiasis ct justification insurance",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ hours/days history of flank pain / loin-to-groin pain.\n\nPain located on the right / left side, radiating to ______.\n\nAssociated with nausea / vomiting / hematuria / urinary symptoms as documented.\n\nPrior history of kidney stones: yes / no - if yes, prior management ______.\n\nDenied fever, rigors, persistent vomiting, anuria, syncope, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress / appears uncomfortable, moving restlessly - typical for renal colic.\nGCS 15/15.\nVital signs reviewed, afebrile / febrile as documented.\n\nPA: soft, lax, no guarding, no rigidity, no rebound tenderness, no peritonism.\n\nRenal angle: right / left renal angle tenderness documented / no renal angle tenderness.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.",
    "mdm": "Differential diagnoses considered including ureteric stone/renal colic, pyelonephritis, UTI, AAA, appendicitis, diverticulitis, and gynecological/testicular pathology if applicable.\n\nUrine results, renal function, inflammatory markers and imaging reviewed if performed.\n\nNo evidence of infected obstructed system, sepsis, renal failure, solitary kidney obstruction, uncontrolled pain or persistent vomiting requiring admission at present.",
    "discharge": "Feels better.\n\nAnalgesia, hydration, urine straining advice, and urology/primary care follow-up explained.\n\nSafety ER return instructions explained including fever, rigors, worsening pain, uncontrolled vomiting, inability to pass urine, reduced urine output, dizziness/syncope, or any other concerns.",
    "insurance": "Patient presenting with ___ hours/days of right / left flank pain radiating to the groin / lower abdomen, associated with hematuria / urinary frequency / nausea and vomiting.\n\nClinical examination demonstrates right / left renal angle tenderness with no peritoneal signs.\n\nUrinalysis shows hematuria / is within normal limits.\n\nClinical presentation is consistent with suspected renal / ureteric colic secondary to urolithiasis.\n\nCT KUB (non-contrast) / CT abdomen and pelvis with contrast is requested to:\n- Confirm or exclude ureteric calculus.\n- Assess for degree of hydronephrosis or ureteric obstruction.\n- Identify stone size and location to guide further urological management.\n- Exclude alternative diagnoses including AAA, appendicitis, or other acute intra-abdominal pathology.\n\nImaging findings will directly determine the need for urological intervention, admission, or safe discharge."
  },
  {
    "category": "Neuro",
    "title": "Dizziness / Vertigo",
    "keywords": "dizziness vertigo bppv stroke cerebellar nystagmus posterior circulation",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of dizziness / vertigo.\n\nDescribed as room-spinning sensation / lightheadedness / imbalance as documented.\n\nTriggered by head movement / position change / standing / not positional as documented.\n\nAssociated with nausea / vomiting as documented.\n\nDenied headache, hearing loss, tinnitus, ear discharge, weakness, numbness, speech difficulty, visual disturbance, chest pain, palpitations, syncope, or loss of consciousness.",
    "exam": "Conscious, alert and oriented, not in respiratory distress.\nGCS 15/15.\n\nPupils equal and reactive to light.\nNo nystagmus.\nNormal extraocular muscle movements.\n\nNegative cerebellar signs.\nNo dysdiadochokinesia.\nNormal finger-to-nose test.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\nPA: soft, lax, non-tender.\n\nCNS:\nPower 5/5 in all four limbs.\nSensation intact bilaterally.\nPlantars downgoing bilaterally.\nGait normal / not assessed due to dizziness as documented.\nReflexes symmetrical.",
    "mdm": "Differential diagnoses considered including BPPV/peripheral vertigo, vestibular neuritis, labyrinthitis, dehydration, arrhythmia, anemia, electrolyte disturbance, posterior circulation stroke, and other central causes as appropriate.\n\nPeripheral and central causes considered, posterior circulation stroke considered.\n\nCurrent neurological examination reassuring with no focal neurological deficit identified.\n\nInvestigations and treatment response reviewed if performed.",
    "discharge": "Feels better.\n\nFollow-up with ENT/physiotherapy/primary care as appropriate explained.\n\nSafety ER return instructions explained including weakness, numbness, speech disturbance, visual loss, severe headache, inability to walk, persistent vomiting, syncope, chest pain, palpitations, worsening symptoms, or any other concerns."
  },
  {
    "category": "GI",
    "title": "Abdominal Pain (General)",
    "keywords": "abdominal pain abdomen pancreatitis appendicitis biliary aaa bowel obstruction acs pe",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of abdominal pain.\n\nPain located in the ______ region, radiating to ______.\n\nAssociated with nausea / vomiting / diarrhea / constipation as documented.\n\nDenied fever, urinary symptoms, chest pain, SOB, syncope, hematemesis, melena, rectal bleeding, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\nVital signs reviewed.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\n\nPA: soft, lax, no distension, tenderness over ______, no guarding, no rigidity, no rebound tenderness, Murphy's sign negative, RIF non-tender, bowel sounds present.",
    "mdm": "Differential diagnoses considered and discussed including pancreatitis, biliary pathology, appendicitis, bowel obstruction, diverticulitis, renal colic, AAA, mesenteric ischemia, ACS, PE and other intra-abdominal or extra-abdominal causes as appropriate to presentation and location of pain.\n\nInvestigations reviewed and explained.\n\nNo evidence of acute surgical abdomen or other emergency condition requiring admission at present based on current assessment.",
    "discharge": "Feels better.\n\nSafety ER return instructions explained including worsening abdominal pain, persistent vomiting, fever, inability to tolerate oral intake, chest pain, SOB, syncope, blood in stool or vomit, or any other concerns.\n\nFollow up with primary care as appropriate."
  },
  {
    "category": "GI",
    "title": "Epigastric / Upper Abdominal Pain",
    "keywords": "epigastric pain upper abdominal pain dyspepsia gastritis biliary pancreatitis acs mimic",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of epigastric / upper abdominal pain.\n\nPain described as ______, burning / cramping / sharp / pressure-like as documented.\n\nRelationship to meals: worse with food / better with food / unrelated as documented.\n\nAssociated with nausea / vomiting / reflux / early satiety as documented.\n\nRadiating to back / chest / shoulder / no radiation as documented.\n\nDenied chest pain, SOB, diaphoresis, palpitations, syncope, hematemesis, melena, weight loss, jaundice, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\nHemodynamically stable, vital signs reviewed.\n\nCVS: S1 + S2, no murmur, regular rate and rhythm, no JVD.\nChest: equal air entry bilaterally, no added sounds, no chest wall tenderness.\n\nPA: soft, lax, epigastric tenderness / non-tender as documented, no guarding, no rigidity, no rebound tenderness, Murphy's sign negative, bowel sounds present.",
    "mdm": "Cardiac causes (ACS, ACS mimicking dyspepsia) actively considered and excluded - ECG and troponin reviewed if performed.\n\nDifferential diagnoses considered including gastritis, dyspepsia, peptic ulcer disease, biliary colic/cholecystitis, pancreatitis, ACS, aortic pathology and other causes of epigastric/upper abdominal pain as appropriate.\n\nInvestigations reviewed and explained if performed.\n\nNo evidence of acute abdomen, ACS or other emergency condition requiring admission at present.",
    "discharge": "Feels better.\n\nDietary advice, medication plan and follow-up explained.\n\nSafety ER return instructions explained including worsening pain, chest pain, SOB, diaphoresis, persistent vomiting, hematemesis, melena, syncope, fever, or any other concerns.\n\nFollow up with primary care as appropriate."
  },
  {
    "category": "GI",
    "title": "Lower Abdominal Pain / Female",
    "keywords": "lower abdominal pain pelvic pain female ectopic pregnancy ovarian torsion pid appendicitis",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of lower abdominal / pelvic pain.\n\nPain located right / left / suprapubic / bilateral, radiating to ______.\n\nLMP: ______. Pregnancy possibility reviewed - beta-hCG pending / negative / positive as documented.\n\nAssociated with nausea / vomiting / vaginal bleeding / discharge / urinary symptoms as documented.\n\nDenied syncope, shoulder tip pain, severe unilateral pain, fever, persistent vomiting, heavy vaginal bleeding, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\nVital signs reviewed.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\n\nPA: soft, lax, lower abdominal / suprapubic / RIF / LIF tenderness over ______ as documented, no guarding, no rigidity, no rebound tenderness, bowel sounds present.\n\nPelvic examination findings documented if performed.",
    "mdm": "Differential diagnoses considered including ectopic pregnancy, ovarian torsion, ruptured ovarian cyst, PID, appendicitis, UTI, renal colic, diverticulitis, primary dysmenorrhea and other gynecological or abdominal causes as appropriate.\n\nPregnancy status and investigations reviewed if performed.\n\nNo evidence of ectopic pregnancy, ovarian torsion or other acute gynecological/surgical emergency requiring admission at present.",
    "discharge": "Feels better.\n\nAnalgesia and follow-up advice explained.\n\nSafety ER return instructions explained including worsening pain, syncope, heavy vaginal bleeding, positive pregnancy test if not already known, fever, persistent vomiting, shoulder tip pain, dizziness, new discharge, or any other concerns.\n\nFollow up with primary care/OB-Gyn as appropriate."
  },
  {
    "category": "Nephro",
    "title": "UTI / Cystitis",
    "keywords": "uti cystitis dysuria frequency urgency urine",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of dysuria, urinary frequency and urgency.\n\nAssociated with suprapubic discomfort / hematuria as documented.\n\nLMP / pregnancy possibility reviewed if applicable.\n\nDenied fever, flank pain, vomiting, rigors, confusion, vaginal discharge, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\nVital signs reviewed, afebrile.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\n\nPA: soft, lax, suprapubic tenderness / non-tender as documented, no guarding, no rigidity, no rebound tenderness.\n\nRenal angle: no renal angle tenderness.",
    "mdm": "Presentation most consistent with urinary tract infection / cystitis.\n\nDifferential diagnoses considered including pyelonephritis, renal colic, STI/urethritis, and pelvic pathology if applicable.\n\nUrine results and investigations reviewed and explained.\n\nAntibiotics prescribed as appropriate according to clinical assessment/local guideline.\n\nNo evidence of pyelonephritis, sepsis, or other complication requiring admission at present.",
    "discharge": "Feels better.\n\nHydration, medication compliance, and follow-up if symptoms persist explained.\n\nSafety ER return instructions explained including fever, flank pain, vomiting, worsening pain, rigors, dizziness/syncope, confusion, reduced urine output, or any other concerns.\n\nFollow up with primary care if symptoms persist."
  },
  {
    "category": "GI",
    "title": "Dysmenorrhea / Painful Periods",
    "keywords": "dysmenorrhea period pain menstrual cramps pelvic pain primary secondary",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with lower abdominal / pelvic pain associated with menstruation.\n\nLMP: ______. Cycle normally regular / irregular.\n\nPain onset: with period / before period, duration ___ days, severity ___/10.\n\nAssociated with nausea / vomiting / diarrhea / back pain as documented.\n\nPrior similar episodes with periods: yes / no.\n\nSexually active: yes / no. Contraception: ______.\n\nPregnancy possibility reviewed - beta-hCG: pending / negative / positive.\n\nDenied fever, abnormal vaginal discharge, dyspareunia, intermenstrual bleeding, syncope, shoulder tip pain, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\nVital signs reviewed, afebrile.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\n\nPA: soft, lax, suprapubic / lower abdominal tenderness as documented, no guarding, no rigidity, no rebound tenderness, bowel sounds present.\n\nPelvic examination findings documented if performed:\nNo cervical motion tenderness.\nNo adnexal tenderness / mass.\nNo abnormal discharge.",
    "mdm": "Presentation most consistent with primary dysmenorrhea.\n\nDifferential diagnoses considered including primary dysmenorrhea, secondary dysmenorrhea (endometriosis, fibroids, adenomyosis), ectopic pregnancy, ovarian torsion, ruptured ovarian cyst, PID, appendicitis, UTI, and renal colic as appropriate.\n\nPregnancy excluded / beta-hCG negative.\n\nInvestigations reviewed if performed.\n\nNo evidence of ectopic pregnancy, ovarian torsion, or other acute surgical/gynecological emergency requiring admission at present.",
    "discharge": "Feels better.\n\nAnalgesia (NSAIDs / paracetamol) and follow-up advice explained.\n\nSafety ER return instructions explained including worsening or severe pain, syncope, heavy vaginal bleeding, positive pregnancy test, fever, persistent vomiting, shoulder tip pain, abnormal discharge, or any other concerns.\n\nFollow up with primary care/OB-Gyn for further evaluation if recurrent or worsening symptoms."
  },
  {
    "category": "GI",
    "title": "Anal Fissure",
    "keywords": "anal fissure constipation rectal pain hard stools dre perianal hemorrhoids",
    "history": "Patient is a ___ -year-old male / female, no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of anal pain.\n\nAssociated with constipation and passage of hard stools.\n\nDenied fever, abdominal pain, vomiting, per rectal bleeding, anal discharge, or other symptoms.",
    "exam": "Conscious, alert and oriented x3, not in distress.\nGCS 15/15.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\nPA: soft, lax, non-tender, not distended, bowel sounds present.\n\nDigital Rectal Examination (DRE):\nAnal fissure located at ______ position (posterior / anterior).\nNo external hemorrhoids.\nNo perianal abscess.\nNo mass palpated.",
    "mdm": "Presentation consistent with acute anal fissure, likely secondary to constipation and passage of hard stools.\n\nDifferential diagnoses considered including anal fissure, hemorrhoids, perianal abscess, inflammatory bowel disease, and other anorectal pathology as appropriate.\n\nNo evidence of abscess, bleeding requiring intervention, or other surgical emergency at present.\n\nManagement plan discussed including dietary advice, hydration, stool softeners, topical analgesia, and sitz baths.",
    "discharge": "Feels better.\n\nAdvised increased fluid intake, high-fiber diet, and stool softeners to prevent recurrence.\n\nTopical analgesia / topical GTN / topical diltiazem prescribed as appropriate.\n\nSitz baths advised twice daily.\n\nSafety ER return instructions explained including worsening pain, per rectal bleeding, fever, swelling or discharge around the anal area, or any other concerns.\n\nFollow up with primary care / colorectal surgery if symptoms persist or worsen."
  },
  {
    "category": "Neuro",
    "title": "Headache",
    "keywords": "headache migraine sah thunderclap meningitis tension cluster neuro ct",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with headache for ___ hours/days.\n\nLocated: frontal / temporal / occipital / diffuse / unilateral / bilateral.\n\nDescribed as: throbbing / pressure / sharp / worst headache of life, severity ___/10.\n\nOnset: sudden thunderclap / gradual.\n\nSimilar to prior headaches: yes / no — different from usual as documented.\n\nAssociated with nausea / vomiting / photophobia / phonophobia / visual aura as documented.\n\nDenied fever, neck stiffness, seizure, loss of consciousness, weakness, numbness, speech disturbance, visual loss, recent trauma, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\n\nPupils equal and reactive to light.\nNo papilledema on fundoscopy if performed.\nNo facial asymmetry.\nSpeech normal.\n\nNeck: no neck stiffness, no meningism, Kernig's sign negative, Brudzinski's sign negative.\n\nCNS: power 5/5 in all four limbs, sensation intact bilaterally, plantars downgoing bilaterally, reflexes symmetrical, normal finger-to-nose test, gait normal.\n\nNo focal neurological deficit identified.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.",
    "mdm": "Red flag features reviewed — thunderclap onset, fever/meningism, focal neurology, papilledema, immunocompromised, anticoagulated, progressive worsening, new onset >50 years — present / absent as documented.\n\nDifferential diagnoses considered including SAH, ICH, meningitis/encephalitis, temporal arteritis, intracranial mass lesion, migraine, tension headache, cluster headache, and other primary/secondary headache causes as appropriate.\n\nInvestigations and CT head reviewed if performed.\n\nNo evidence of acute neurological emergency requiring admission at present based on current assessment.",
    "discharge": "Feels better.\n\nAnalgesia and headache management plan explained.\n\nSafety ER return instructions explained including sudden severe thunderclap headache, worst headache of life, fever, neck stiffness, confusion, seizure, weakness, numbness, visual loss, speech disturbance, syncope, worsening or persistent headache, or any other concerns.\n\nFollow up with primary care/neurology as appropriate.",
    "insurance": "CT HEAD / BRAIN — INSURANCE / IMAGING JUSTIFICATION\n\nPatient presenting with a new-onset headache with progressive worsening and inadequate response to analgesia.\n\nCT brain is clinically indicated to exclude acute intracranial pathology, including intracranial hemorrhage, mass effect, or space-occupying lesion, despite a currently normal neurological examination.\n\nImaging is required to identify or exclude a secondary intracranial cause and guide further management and disposition."
  },
  {
    "category": "Neuro",
    "title": "Neck Pain",
    "keywords": "neck pain cervical spine meningitis stiffness torticollis trauma c-spine",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with ___ days history of neck pain.\n\nOnset: traumatic / atraumatic / gradual / sudden.\n\nMechanism if traumatic: ______.\n\nPain located: midline / paraspinal / right / left, radiating to ______.\n\nAssociated with headache / fever / arm numbness / weakness / tingling / reduced ROM as documented.\n\nDenied fever, rash, jaw claudication, visual symptoms, weakness, saddle anesthesia, bowel or bladder dysfunction, IV drug use, malignancy history, or other symptoms.",
    "exam": "Conscious, alert and oriented, not in distress.\nGCS 15/15.\nVital signs reviewed.\n\nNeck: midline cervical tenderness / paraspinal tenderness over ______, range of movement limited by pain / full ROM, no step-off deformity, no swelling, no skin changes.\n\nNo neck stiffness / meningism.\nKernig's sign negative.\nBrudzinski's sign negative.\n\nCNS: power 5/5 in all four limbs, sensation intact bilaterally, plantars downgoing bilaterally, reflexes symmetrical, no focal neurological deficit.\n\nUpper limb neurovascular: pulses palpable, capillary refill < 2 seconds, sensation and motor function intact.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.",
    "mdm": "Differential diagnoses considered including mechanical neck pain, cervical radiculopathy, cervical spine fracture/injury, meningitis, SAH, temporal arteritis, carotid/vertebral artery dissection, deep neck space infection, malignancy, and other causes as appropriate.\n\nRed flags reviewed — fever, trauma, neurological deficit, malignancy history, IV drug use, anticoagulation — present / absent as documented.\n\nImaging considered/reviewed if performed.\n\nNo evidence of cervical spine fracture, cord compression, meningism, or other emergency pathology requiring admission at present.",
    "discharge": "Feels better.\n\nAnalgesia, activity advice, and follow-up explained.\n\nSafety ER return instructions explained including fever, worsening pain, arm or leg weakness/numbness, difficulty walking, difficulty swallowing, breathing difficulty, severe headache, confusion, or any other concerns.\n\nFollow up with primary care/physiotherapy as appropriate."
  },
  {
    "category": "Neuro",
    "title": "Syncope / Near Syncope",
    "keywords": "syncope near syncope collapse faint vasovagal arrhythmia seizure acs pe presyncope",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED following syncope / near syncope.\n\nEpisode occurred ___ hours ago while ______.\n\nProdrome: nausea / diaphoresis / tunnel vision / palpitations / chest pain / none as documented.\n\nLoss of consciousness: yes / no, duration ______.\n\nSeizure activity / tongue biting / incontinence: yes / no.\n\nReturn to baseline: immediate / gradual / not yet.\n\nWitnessed: yes / no — description ______.\n\nDenied recent dehydration, blood loss, prolonged standing, head injury, neurological symptoms, or other symptoms.",
    "exam": "Conscious, alert and oriented, back to baseline.\nGCS 15/15.\nVital signs reviewed.\nOrthostatic vitals performed if applicable.\n\nCVS: S1 + S2, no murmur, regular rate and rhythm, no JVD, peripheral pulses palpable.\nChest: equal air entry bilaterally, no added sounds.\nPA: soft, lax, non-tender.\n\nCNS: pupils equal and reactive to light, no facial asymmetry, power 5/5 in all four limbs, sensation intact bilaterally, plantars downgoing bilaterally, reflexes symmetrical, no focal neurological deficit.\n\nTrauma assessment: no head injury or other injuries identified.",
    "mdm": "Differential diagnoses considered including vasovagal syncope, orthostatic hypotension, dehydration, arrhythmia, ACS, PE, structural cardiac disease, seizure, hypoglycemia, anemia, hemorrhage, and other causes as appropriate.\n\nECG reviewed.\n\nHigh-risk features reviewed — exertional syncope, syncope with chest pain/palpitations, no prodrome, family history of sudden cardiac death, structural heart disease, abnormal ECG — present / absent as documented.\n\nInvestigations reviewed if performed.\n\nRisk stratification performed. No current evidence of high-risk cause requiring admission at present based on current assessment.",
    "discharge": "Patient back to baseline, feels well.\n\nAdvised hydration, avoiding prolonged standing, and trigger avoidance where applicable.\n\nDriving advice discussed as per local guidelines.\n\nSafety ER return instructions explained including recurrent syncope, chest pain, palpitations, SOB, seizure activity, neurological symptoms, injury, or any other concerns.\n\nFollow up with primary care/cardiology as appropriate."
  },
  {
    "category": "MSK",
    "title": "Cervicalgia / Neck Spasm",
    "keywords": "cervicalgia neck pain spasm shoulder pain cervical radiculopathy stiff neck",
    "history": "Patient no past medical illness, no known drug allergies.\n\nPresented to the ED with right / left neck pain radiating to the right / left shoulder for ___ days.\n\nDescribed as a spasm / stiffness in the neck and shoulder area.\n\nPain worse on turning to the right / left side.\n\nNo history of trauma or fall.\n\nDenied numbness, weakness, fever, headache, or other symptoms.",
    "exam": "Conscious, alert and oriented x3, not in distress.\nGCS 15/15.\n\nNeck: restricted range of movement to the right / left side secondary to pain.\nNo midline cervical tenderness.\nParaspinal muscle tenderness / spasm over right / left side.\nNo step-off deformity.\nNo swelling.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\n\nCNS:\nPower 5/5 in all four limbs.\nSensation intact bilaterally.\nNo focal neurological deficits.\nIntact peripheral pulses.",
    "mdm": "Presentation consistent with cervicalgia / mechanical neck pain with muscle spasm.\n\nDifferential diagnoses considered including cervical radiculopathy, cervical disc herniation, meningitis, SAH, and other causes of neck pain as appropriate.\n\nRed flags reviewed — fever, trauma, progressive neurological deficit, malignancy — absent.\n\nNo evidence of cord compression, meningism, or other emergency pathology requiring admission or urgent imaging at present.",
    "discharge": "Feels better.\n\nAnalgesia, muscle relaxant if prescribed, and physiotherapy follow-up advised.\n\nAdvised gentle range of motion exercises, heat application, and activity modification.\n\nSafety ER return instructions explained including new or worsening arm numbness or weakness, severe headache, fever, neck stiffness, inability to move neck, or any other concerns.\n\nFollow up with primary care/physiotherapy as appropriate."
  },
  {
    "category": "Nephro",
    "title": "Acute Urinary Retention",
    "keywords": "acute urinary retention aur bph foley catheter bladder prostate",
    "history": "Patient is a ___ -year-old male, known to have benign prostatic hyperplasia (BPH) on regular treatment, no known drug allergies.\n\nPresented to the ED with acute urinary retention since ______.\n\nPrevious similar episode: yes — approximately ___ ago / no prior episodes.\n\nDenied chest pain, shortness of breath, fever, hematuria, or dysuria.",
    "exam": "Conscious, alert and oriented x3, in pain.\nGCS 15/15.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no added sounds.\n\nPA: soft, lax, distended bladder palpable approximately ___ finger-breadth(s) below the umbilicus, non-tender / tender on palpation.\n\nExternal genitalia: no visible abnormality, no phimosis, no meatal stenosis.",
    "mdm": "Presentation consistent with acute urinary retention in the context of known BPH.\n\nDifferential diagnoses considered including BPH, urethral stricture, constipation, medication-induced retention, neurogenic bladder, and other causes as appropriate.\n\nRelevant investigations sent including urine analysis, renal function, PSA if applicable, and other bloods as clinically indicated.\n\nUrinary catheterization performed as documented.",
    "discharge": "Under aseptic technique, urethral catheterization was performed.\n\nFoley catheter size ___ Fr inserted atraumatically.\n\nImmediate clear / blood-stained urine drained upon insertion.\n\nBalloon inflated with 10cc / 30cc of sterile water and catheter secured.\n\nTotal urine drained: approximately ___ mls.\n\nPatient's pain and discomfort improved significantly following catheterization.\n\nLaboratory investigations sent as documented.\n\nPatient and family educated regarding catheter care.\n\nSafety ER return instructions explained including fever, rigors, reduced or absent urine output via catheter, worsening pain, hematuria, or any other concerns.\n\nFollow up with urology arranged / advised for further management of underlying BPH.",
    "insurance": "ORDERS / PROCEDURE CODES\n\nCatheterization Procedure:\n- Catheterization-Foley — Code: 8134B\n\nEquipment:\n- Catheter Holder / Foley StatLock (FOL0101CE) — Code: UR3292\n\nLaboratory:\n- Urine analysis / urine culture: ______\n- Renal function (U/C/E): ______\n- CBC: ______\n- PSA (if applicable): ______\n- Other: ______"
  },
  {
    "category": "Trauma",
    "title": "Extremity Injury / Sprain / Suspected Fracture",
    "keywords": "extremity injury sprain strain fracture trauma fall twist twisted ankle foot knee hand wrist elbow shoulder finger toe forearm upper limb lower limb swelling tenderness xray",
    "history": "Patient is a ___-year-old male/female, known to have ______ / medically free, with no known drug allergies / allergy to ______.\n\nPresented to the ED following an injury to the right / left ______ approximately ___ minutes/hours/days prior to presentation.\n\nMechanism of injury: fall / twisting injury / direct trauma / sports injury / other: ______.\n\nPatient reports pain over ______, associated with swelling / bruising / difficulty weight-bearing / painful movement as documented.\n\nAble / unable to ambulate following the injury if lower limb.\n\nDenied head injury, loss of consciousness, neck/back pain, other limb injuries, numbness, weakness, or other symptoms.",
    "exam": "Conscious, alert and oriented x3, not in distress.\nGCS 15/15.\nVital signs reviewed.\n\nRight / Left Upper / Lower Limb:\nTenderness over ______.\nSwelling over ______ / no significant swelling.\nBruising / no bruising.\nNo obvious deformity.\nNo open wounds.\n\nRange of motion: full / restricted secondary to pain.\n\nDistal neurovascular examination intact:\n- Peripheral pulses palpable.\n- Capillary refill < 2 seconds.\n- Sensation intact.\n- Motor function intact.\n\nNo tenderness over the joint above or below the affected area.\n\nFor lower-limb injury: able / unable to weight-bear and ambulate.",
    "mdm": "Presentation consistent with acute right / left ______ injury following ______.\n\nDifferential diagnoses considered include soft-tissue injury, sprain/strain, contusion, fracture, dislocation, tendon/ligament injury, and other traumatic pathology as appropriate.\n\nDistal neurovascular status intact with no evidence of open fracture or acute neurovascular compromise.\n\nX-ray of ______ requested / reviewed as clinically indicated.",
    "discharge": "X-ray demonstrates no acute fracture or dislocation / findings discussed as documented.\n\nClinical impression: soft-tissue injury / sprain / contusion of ______.\n\nAnalgesia, rest, ice, elevation, and activity modification explained as appropriate.\n\nSplint / ankle support / arm sling / buddy strapping / other support provided as indicated.\n\nSafety ER return instructions explained including worsening pain or swelling, increasing bruising, numbness, weakness, change in skin color or temperature, inability to move the affected limb/digits, inability to weight-bear, or any other concerns.\n\nFollow up with orthopedics / primary care as appropriate.",
    "insurance": "X-RAY — IMAGING / INSURANCE JUSTIFICATION\n\nPatient sustained an acute traumatic injury to the right / left ______ with localized pain and tenderness over ______, associated with swelling / restricted range of motion / difficulty weight-bearing as documented.\n\nPlain radiography is clinically indicated to exclude acute fracture, dislocation, or other bony injury and to guide further management."
  },
  {
    "category": "Handover",
    "title": "Handover — Case Received From Previous Shift",
    "keywords": "handover received previous shift case received endorsed received pending investigations reassessment disposition",
    "history": "",
    "exam": "",
    "mdm": "",
    "discharge": "CASE RECEIVED / HANDOVER\n\nCase received from Dr. ______ at ______.\n\nA case of ___-year-old male/female, known to have ______ / medically free, presenting with ______.\n\nWorking impression: ______.\n\nWorkup performed prior to handover:\n- Labs: ______\n- ECG: ______\n- Imaging: ______\n- Treatment given: ______\n\nResults reviewed so far: ______.\n\nPending: ______.\n\nPatient reassessed following handover. Currently ______.\n\nPlan: Review pending investigations, reassess clinically, and determine final disposition accordingly.\n\nHandover received from: Dr. ______\nHandover received by: Dr. Husain Dhaif\nTime: ______"
  },
  {
    "category": "Handover",
    "title": "Handover — Case Endorsed To Next Shift",
    "keywords": "handover endorsed next shift case endorsement pending investigations reassessment disposition handover given",
    "history": "",
    "exam": "",
    "mdm": "",
    "discharge": "CASE ENDORSEMENT / HANDOVER\n\nA case of ___-year-old male/female, known to have ______ / medically free, presenting with ______.\n\nWorking impression: ______.\n\nWorkup performed:\n- Labs: ______\n- ECG: ______\n- Imaging: ______\n- Treatment given: ______\n\nResults reviewed so far: ______.\n\nPending: ______.\n\nPatient currently ______.\n\nCase endorsed to Dr. ______ for review of pending investigations, clinical reassessment, and final disposition.\n\nHandover given by: Dr. Husain Dhaif\nHandover received by: Dr. ______\nTime: ______"
  },
  {
    "category": "Medicolegal",
    "title": "Head Injury — External CT Request / GP Referral Documentation",
    "keywords": "head injury ct head external gp referral medicolegal documentation neurosurgical smc transfer",
    "history": "",
    "exam": "",
    "mdm": "",
    "discharge": "Prior to the patient's presentation to the Emergency Department, I was contacted by Dr. ______ from ______, who informed me that she/he had assessed the patient and had requested a CT head. She/he stated that the patient would attend the Emergency Department following completion of the CT scan.\n\nI explained to Dr. ______ that, irrespective of the CT head findings, if the patient remained symptomatic following the reported head injury, she/he would require further clinical assessment and, depending on the clinical findings, neurosurgical evaluation. I further explained that neurosurgical services are not available at our facility and that, if neurosurgical assessment were indicated, the patient would ultimately require referral/transfer to SMC.\n\nDr. ______ stated that this was the approach being followed by herself/himself and the doctors at their facility.\n\nThe patient was also informed that a normal/negative CT head would not necessarily exclude the need for further assessment, particularly if the patient remained symptomatic, and that neurosurgical assessment may be required.\n\nThe patient was informed that neurosurgical services are not available at our facility and that the patient would need to be referred to SMC for neurosurgical assessment if indicated.\n\nThe CT head report and imaging were provided to the patient, with the imaging supplied on CD.\n\nA referral letter was also provided.\n\nThe patient was advised to attend SMC for further assessment, particularly in view of the ongoing symptoms and the lack of on-site neurosurgical services at our facility."
  },
  {
    "category": "Allergy",
    "title": "Urticaria / Acute Allergic Reaction",
    "keywords": "urticaria hives allergic reaction allergy rash wheals pruritus itching angioedema facial swelling",
    "history": "Patient is a ___-year-old male / female, no past medical illness, no known drug allergies / known allergy to ______.\n\nPresented to the ED with ___ hours/days history of an itchy rash.\n\nRash started over ______ and subsequently spread to ______.\n\nPossible trigger/exposure: food / medication / insect bite or sting / topical product / environmental exposure / unknown.\n\nAssociated with facial swelling / lip swelling / throat tightness / shortness of breath / none as documented.\n\nDenied tongue swelling, voice change, difficulty swallowing, wheeze, dizziness, syncope, abdominal pain, vomiting, fever, or other symptoms as documented.\n\nPrevious similar allergic reaction / urticaria: yes / no.",
    "exam": "Conscious, alert and oriented x3, not in distress.\nGCS 15/15.\nHemodynamically stable, vital signs reviewed.\n\nSkin: urticarial wheals / erythematous raised pruritic rash over ______, blanching on pressure as documented.\n\nNo angioedema of the lips, tongue, or face / angioedema present as documented.\n\nAirway patent. No stridor, voice change, drooling, or visible tongue swelling.\n\nCVS: S1 + S2, no murmur.\nChest: equal air entry bilaterally, no wheeze, no added sounds.\nPA: soft, lax, non-tender.",
    "mdm": "Presentation consistent with acute urticaria / allergic reaction.\n\nPotential triggers reviewed including food, medications, insect bites/stings, contact exposures, and idiopathic causes.\n\nPatient assessed specifically for features of anaphylaxis including airway compromise, respiratory involvement, hypotension/circulatory compromise, and significant gastrointestinal symptoms.\n\nNo current clinical features of anaphylaxis / systemic compromise identified at present unless otherwise documented.\n\nTreatment given and response reassessed as documented.",
    "discharge": "Symptoms improved / stable following treatment and observation as documented.\n\nPossible trigger avoidance discussed where identifiable. Medication instructions explained.\n\nSafety ER return instructions explained including difficulty breathing, throat tightness, tongue or lip swelling, voice change, wheeze, dizziness, syncope, rapidly worsening rash, persistent vomiting, or any other concerns.\n\nFollow up with primary care / allergy clinic as appropriate."
  },
  {
    "category": "Allergy",
    "title": "Anaphylaxis",
    "keywords": "anaphylaxis severe allergic reaction allergy adrenaline epinephrine angioedema stridor wheeze hypotension shock",
    "history": "Patient is a ___-year-old male / female, known allergy to ______ / no known drug allergies.\n\nPresented to the ED with an acute allergic reaction following suspected exposure to ______.\n\nOnset approximately ___ minutes/hours prior to presentation.\n\nSymptoms include urticarial rash / flushing / facial swelling / lip or tongue swelling / throat tightness / voice change / difficulty breathing / wheeze / abdominal pain / vomiting / dizziness / syncope as documented.\n\nTreatment given prior to arrival: none / adrenaline auto-injector / antihistamine / other: ______.\n\nPrior history of anaphylaxis: yes / no.\nAdrenaline auto-injector prescribed/carried: yes / no.",
    "exam": "Conscious / reduced level of consciousness as documented.\nGCS ___/15.\n\nHemodynamically stable / unstable as documented.\nHR: ___ bpm. BP: ___/___ mmHg. SpO2: ___% on room air / oxygen.\n\nSkin: urticarial rash / flushing / angioedema over ______ as documented.\n\nAirway: patent / compromised as documented.\nAngioedema of lips / tongue / face: present / absent.\nStridor: present / absent.\nVoice change: present / absent.\n\nBreathing: equal air entry bilaterally / reduced air entry as documented. Wheeze: present / absent. Respiratory distress: present / absent.\n\nCVS: S1 + S2, tachycardia / normal rate, no murmur. Peripheral perfusion and capillary refill assessed.\n\nPA: soft, lax, non-tender / abdominal tenderness as documented.",
    "mdm": "Clinical presentation concerning for / consistent with anaphylaxis following suspected exposure to ______.\n\nAirway, breathing and circulation assessed immediately with continuous reassessment.\n\nIM adrenaline administered as documented, with additional supportive treatment and repeat dosing if clinically indicated. Oxygen, IV access, fluids and adjunctive medications provided as appropriate to the patient's condition and local protocol.\n\nResponse to treatment documented with repeat vital signs and reassessment of airway, respiratory, cardiovascular, skin and gastrointestinal features.\n\nPatient requires appropriate observation following clinical resolution, with escalation/admission as indicated by severity, treatment response, recurrence of symptoms, comorbidities and local protocol.",
    "discharge": "Following treatment and an appropriate period of observation, patient remained clinically stable with resolution / significant improvement of symptoms as documented.\n\nSuspected trigger and avoidance advice discussed. Adrenaline auto-injector use / prescription and emergency action plan discussed where appropriate.\n\nSafety ER return instructions explained including recurrent rash with breathing difficulty, throat tightness, tongue/lip swelling, wheeze, dizziness, syncope, persistent vomiting, or any recurrence of symptoms.\n\nFollow up with primary care / allergy-immunology clinic as appropriate."
  }
];
